version: '3.7'

services:
  nginx-service:
    container_name: pyconmicroservices-nginx-service
    hostname: nginx-service
    build: ./nginx
    ports:
        - 5052:5052
        - 5051:5051
    restart: always

  capitalize-service:
    container_name: pyconmicroservices-capitalize-service
    build: ./capitalize
    hostname: capitalize-service
    restart: always
    depends_on:
      - nginx-service

  checklowercase-service:
    container_name: pyconmicroservices-checklowercase-service
    build: ./checklowercase
    hostname: checklowercase-service
    restart: always
    depends_on:
      - nginx-service

  checkuppercase-service:
    container_name: pyconmicroservices-checkuppercase-service
    build: ./checkuppercase
    hostname: checkuppercase-service
    restart: always
    depends_on:
      - nginx-service

  generatepassword-service:
    container_name: pyconmicroservices-generatepassword-service
    build: ./generatepassword
    hostname: generatepassword-service
    restart: always
    depends_on:
      - nginx-service

  lowercase-service:
    container_name: pyconmicroservices-lowercase-service
    build: ./lowercase
    hostname: lowercase-service
    restart: always
    depends_on:
      - nginx-service

  titlecase-service:
    container_name: pyconmicroservices-titlecase-service
    build: ./titlecase
    hostname: titlecase-service
    restart: always
    depends_on:
      - nginx-service


  swapcase-service:
    container_name: pyconmicroservices-swapcase-service
    build: ./swapcase
    hostname: titlecase-service
    restart: always
    depends_on:
      - nginx-service
